### ISSUE TITLE
v6 not starting

### ISSUE THREAD

**Issue by ghost** [NodeMC/NodeMC-CORE#27]
I am running the master branch version with no problems :-) But i tried the v6 fork and it will not start:

**Node** v6.2.2

npm install gives the following warnings:

``` npm
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

node server gives:

``` js
Failed to read config. This is OK on first run.
Current version: 6.0.0
main: INIT stage 0 (preinit): Started
main: INIT stage 0 (preinit): Finished
main: INIT stage 1 (express::construct): Started
main: INIT stage 1: mount route auth on /v2/auth
main: INIT stage 1: mount route download on /v2/download
main: INIT stage 1: mount route files on /v2/files
main: INIT stage 1: mount route firstrun on /v2/firstrun
main: INIT stage 1: mount route server on /v2/server
TypeError: Cannot read property 'close' of undefined
    at process.on.e (/Users/Tristan/Minecraft/MC/server.js:219:22)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (node.js:258:21)
Failed to close the Minecraft server log stream.
/Users/Tristan/Minecraft/MC/lib/express.js:99
        throw err;
        ^

ReferenceError: server is not defined
    at Object.<anonymous> (/Users/Tristan/Minecraft/MC/backend/routes/server.js:13:47)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/Tristan/Minecraft/MC/lib/express.js:76:24
    at /Users/Tristan/Minecraft/MC/node_modules/async/dist/async.js:4637:20
```

**Comment by mdcfe** [comment]
v6 is unstable and mostly untested. If you're running a production server, use v5.1 in the `master` branch.

**Comment by mdcfe** [comment]
(However, we'll look into this, looks like a server wrapper bug)
