### ISSUE TITLE
Error thrown on last step of setup

### ISSUE THREAD

**Issue by necrogami** [NodeMC/NodeMC-CORE#4]
---

| ~/code/NodeMC-CORE @ Antons-MacBook-Pro (necrogami) 
| => node Main.js 
Naviagte to http://localhost:3000 to set up NodeMC.
Generating new API key
New API key saved
Error: ENOENT: no such file or directory, mkdir ''
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at /Users/necrogami/code/NodeMC-CORE/Main.js:302:56
    at Layer.handle [as handle_request](/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/layer.js:95:5)
    at /Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/index.js:271:10)
Error: ENOENT: no such file or directory, mkdir ''
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at /Users/necrogami/code/NodeMC-CORE/Main.js:302:56
    at Layer.handle [as handle_request](/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/layer.js:95:5)
    at /Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/necrogami/code/NodeMC-CORE/node_modules/express/lib/router/index.js:271:10)

**Comment by gmemstr** [comment]
Looking into this, most likely because NodeMC can't recursively create the jarfile directory - or you left it blank. Investigating.

**Comment by gmemstr** [comment]
Fixed as of commit [#bf14cc9](https://github.com/NodeMC/NodeMC-CORE/commit/bf14cc99fb8f26fb198efeb17af10ffba10ec995). Thanks for all the bug reports!
